### PR TITLE
Update couchdb_peruser package for CouchDB 2.0

### PR DESCRIPTION
**Pull request by guillett**
I tried to set up CouchDB 2.0 with couchdb_peruser enabled. I saw (in
previous email in the user-archive) that it haven't been tested with 2.0. At the
same time, tests are passing but when using CouchDB normally user creation
does not trigger a database creation.

I investigated the logic behind and the mechanisms is only working when
users are added to the node-only _users database. Users added to the
cluster are not watched for systematic database creation.

The previous set up is relatively strange, as user databases (userdb-xxxx)
are added to the cluster but not to the local node (they are sharded).

Previously, couch_peruser relies on couch_changes:handle_db_changes which is
local-node specific and I do not find an equivalent for the cluster.

I hack together an updated version of couch_peruser that spawn_opt an
couch_changes:handle_db_changes for each local shard of the cluster
authentication_db.

Would that approach be ok ?
It there any point in keeping the previous logic working ? (Local users but
clustered user dbs.)

I am pretty new at CouchDB and at Erlang so pardon my basic understanding
of the different mechanisms.

### CODE REVIEW

**Comment by cristianszwarc** [comment]
following..

**Comment by kxepal** [comment]
LGFM. 
@iilyak, @rnewson, @nickva, could you check this please?

**Comment by guillett** [comment]
Do not merge this PR just yet.
I need to reproduce and mitigate/fix some issues I had (from memory, crash on initial start-up before cluster set-up) and check that everything is in line on subsequent start-ups.
I will push updates ASAP (probably later today).

**Comment by kxepal** [comment]
@guillett 
Thanks for follow up! No worries, leave a note when it will be ready for final testing and merge then.

**Comment by guillett** [comment]
@kxepal 
Thanks, I had another look and I would like some feedback from knowledgable people. I confirm, if the instance is started with peruser enabled and without the underlying user table, it crashes.

* I thought that I could watch _all_dbs via ```couch_changes:handle_db_changes``` but I can't (at least, I didn't manage).
* I wanted to use the same strategy as ```chttpd_auth_cache```  (that is to ping the system every 5 seconds to check if it is ready) but I don't think a plugin like peruser is a place to have such logic.

That is why, I finally *simply* I amended the logic to **disable** the plugin when the user database is missing, it generates a ```[warning]``` and the configuration change ```[notice]``` also contains the reason (*_users is missing*).

**Comment by jacksonrayhamilton** [comment]
@guillett thank you for stepping up and contributing this! I ran into this recently and was wondering how anyone actually used CouchDB 2.0 without per-user document read authorization.

**Comment by jacksonrayhamilton** [comment]
I am having trouble getting this to work. I've tried replacing the `src/couch_peruser` directory in the `apache-couchdb-2.0.0.tar.gz` release with this branch, and compiled couchdb with `make release` and enabled `couch_peruser` in Couch's `etc/local.ini` and restarted my server, but am still not seeing per-user databases being created (when I create new users).

BTW, this is how I installed couchdb on my Debian 8 system:

```bash
sudo apt-get --no-install-recommends -y install \
    build-essential pkg-config erlang \
    libicu-dev libmozjs185-dev libcurl4-openssl-dev
cd ~/programs
wget http://mirror.metrocast.net/apache/couchdb/source/2.0.0/apache-couchdb-2.0.0.tar.gz
tar xzf apache-couchdb-2.0.0.tar.gz
cd apache-couchdb-2.0.0
rm -rf src/couch_peruser
git clone https://github.com/guillett/couchdb-peruser.git src/couch_peruser
./configure
make release
sudo adduser --system \
     --shell /bin/bash \
     --group --gecos \
     "CouchDB Administrator" couchdb

sudo cp -a rel/couchdb/. /home/couchdb
sudo chown -R couchdb:couchdb /home/couchdb
sudo find /home/couchdb -type d -exec chmod 0770 {} \;
sudo find /home/couchdb/etc -type f -exec chmod 0644 {} \;

# To run:
# sudo -i -u couchdb /home/couchdb/bin/couchdb
# Visit http://localhost:5984/_utils/index.html#verifyinstall
# Then visit http://127.0.0.1:5984/_utils#setup to set up a single-node instance
# with the username "admin" and the password "password".

npm i -g add-cors-to-couchdb
add-cors-to-couchdb -u admin -p password

# Edit /home/couchdb/etc/local.ini and enable couch_peruser. And restart the server.
```

I used the Node.js `pouchdb-authentication` plugin in my application, using its `db.signup` method to create users. My application can create new users, but no `user-abc123` databases show up.

**Comment by guillett** [comment]
@jacksonrayhamilton Thanks for your message and sorry to hear that you have trouble using the branch.

I haven't tested with the package on CouchDB but only from github master.

Here is what I have done and that seems to work (I have no idea why it is not working with the package):
```
set -e
set -v
git clone git@github.com:guillett/couchdb-peruser.git
cd couchdb-peruser
git clone https://github.com/apache/couchdb
cd couchdb
./configure --disable-docs --disable-fauxton
cp -R ../src ./src/couch_peruser && cp -R ../test ./src/couch_peruser
make release
./rel/couchdb/bin/couch
```

In a different shell (sorry that one is a bit dirty):
```
#!/bin/sh
set -e
set -v
# Should return full config
res=`curl -sX GET http://localhost:5984/_node/couchdb@localhost/_config`
if [[ $res == '{"error":"unauthorized","reason":"You are not a server admin."}' ]]; then
  res=`curl -sX DELETE http://localhost:5984/_node/couchdb@localhost/_config/admins/tom -H "Authorization: Basic dG9tOnRvbQ=="`
  [[ `echo $res|wc -c` -gt 50 ]]
  res=`curl -sX GET http://localhost:5984/_node/couchdb@localhost/_config`
fi
[[ `echo $res|wc -c` -gt 1000 ]]
[[ `curl -sX GET http://localhost:5984/_cluster_setup` == '{"state":"cluster_disabled"}' ]]
[[ `curl -sX POST http://localhost:5984/_cluster_setup \
  -d '{"action":"enable_cluster","username":"tom","password":"tom","bind_address":"0.0.0.0","port":5984}' \
  -H 'Content-Type: application/json'` == '{"ok":true}' ]]
[[ `curl -sX POST http://localhost:5984/_cluster_setup \
  -d '{"action":"finish_cluster"}' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Basic dG9tOnRvbQ=="` == '{"ok":true}' ]]

curl -X PUT http://localhost:5984/_node/couchdb@localhost/_config/couch_peruser/enable \
   --data '"true"' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Basic dG9tOnRvbQ=="

 curl -X PUT http://localhost:5984/_users/org.couchdb.user:alice -H 'Content-Type: application/json' \
 -d '{"_id": "org.couchdb.user:alice", "name":"alice", "password":"alice", "type":"user", "roles":[]}'

curl http://localhost:5984/_users/_all_docs -H "Authorization: Basic dG9tOnRvbQ=="
curl http://localhost:5984/_all_dbs
```

I get the expected DB ```userdb-616c696365```.

Can you confirm it is not working for you or send some logs. I will try to give the official 2.0 package a try tomorrow.

**Comment by jacksonrayhamilton** [comment]
Whoops! I forgot to checkout the `test` branch on your fork. After I did that and recompiled I'm now seeing per-user databases being created.

**Comment by guillett** [comment]
@jacksonrayhamilton Good to know, I am glad to read that you fixed your issue and than the fix is working for someone else than me.

**Comment by katche70** [comment]
@guillett 
I merged your testbranch
`git clone -b test https://github.com/guillett/couchdb-peruser.git`

But with this my couchdb service is restart every few seconds. You know why?
eb 21 13:30:58 server.ets.com couchdb[14957]: [info] 2017-02-21T13:30:58.242987Z couchdb@localhost <0.209.0> -------- open_result error {error,eacces} for _users
Feb 21 13:30:58 server.ets.com couchdb[14957]: [error] 2017-02-21T13:30:58.243394Z couchdb@localhost <0.246.0> -------- CRASH REPORT Process  (<0.246.0>) with 1 neighbors exited with reason: no match of right hand value {err
Feb 21 13:30:58 server.ets.com couchdb[14957]: [error] 2017-02-21T13:30:58.244675Z couchdb@localhost <0.203.0> -------- Error starting Apache CouchDB:
Feb 21 13:30:58 server.ets.com couchdb[14957]:     {error,{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,auth_cache,{{badmatch,{error,eacces}},[{couch_auth_cache,ensure_users_db_ex
Feb 21 13:30:58 server.ets.com couchdb[14957]: [error] 2017-02-21T13:30:58.246090Z couchdb@localhost <0.212.0> -------- Supervisor couch_secondary_services had child auth_cache started with couch_auth_cache:start_link() at u
Feb 21 13:30:58 server.ets.com couchdb[14957]: [error] 2017-02-21T13:30:58.246350Z couchdb@localhost <0.204.0> -------- Supervisor couch_sup had child couch_secondary_services started with couch_secondary_sup:start_link() at
Feb 21 13:30:58 server.ets.com couchdb[14957]: [error] 2017-02-21T13:30:58.246570Z couchdb@localhost <0.202.0> -------- CRASH REPORT Process  (<0.202.0>) with 0 neighbors exited with reason: {{shutdown,{failed_to_start_child
Feb 21 13:30:58 server.ets.com couchdb[14957]: [info] 2017-02-21T13:30:58.246751Z couchdb@localhost <0.7.0> -------- Application couch exited with reason: {{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,
Feb 21 13:30:58 server.ets.com couchdb[14957]: [os_mon] memory supervisor port (memsup): Erlang has closed
Feb 21 13:30:58 server.ets.com couchdb[14957]: [os_mon] cpu supervisor port (cpu_sup): Erlang has closed

**Comment by guillett** [comment]
@katche70 No ideas. Can you dump your config here? What is your cluster setup? Do you have anything fancy set up?

**Comment by katche70** [comment]
i delete all couchdb files and did a new fresh install. now couchdb service is running fine. 
I acticate 
`
[couch_peruser]
enable = true
`
and restarted service. After adding a new user with pouchdb no new db was created. 
is ist nessesary to configure cluster or single node? 


**edit:**
After adding cluster and adding couch_peruser/enable = true in cluster everything is working fine. 
thx

**Comment by guillett** [comment]
@katche70 You need to have a cluster set up (I tested with single node cluster and that works).

You can either set up your cluster via Fauxton or use a similar strategy I used in https://github.com/apache/couchdb-peruser/pull/3#issuecomment-279244728 (I replicated what Fauxton send to the server using curl calls).

Currently your console should be spammed by couch_auth_cache every 5 seconds or so.
Once your cluster is ready the spam should stop and you should be able to enable the _peruser module.


If that is still not working:
What is your remote DB with PouchDB ? The local node port or the single cluster port ?
Can you see your added user in the user DB ? What is the full URL of your user document ?

**Comment by pinpointpanda** [comment]
@guillett - thanks for this branch. Can confirm I've got this working too (with PouchDB).
@jacksonrayhamilton - thanks for your input, especially that Debian script - made setting this up much quicker!

I had one weird thing - when I was trying to modify 'local.ini' to set 'couch_peruser' to true it wasn't working. I'd save the file, restart the server and check the config. It would be showing 'false' through Fauxton. I'd go back into the 'local.ini' file and... sure enough the setting was changed back to 'false'. I went through this a few times to make sure I was _actually_ saving the file correctly.
Changing 'default.ini' didn't work either. (Note that any other changes I made to the files would stick - just the couch_peruser flag that was being reset each time).

Anyway, in the end, I manually created a '_users' table, made the settings change in 'local.ini', restarted and the change held correctly. Just leaving this note here in case anyone else comes across the same thing!

**Comment by bshikhar13** [comment]
Hi @guillett I followed your instructions. but since I need Fauxton, I used the `./configure` instead of `./configure --disable-docs --disable-fauxton`. Upon `make release` the build fails. Can you please enlighten me what the problem can be?

**Comment by emoryy** [comment]
@guillett I also tried your [instructions](https://github.com/apache/couchdb-peruser/pull/3#issuecomment-279244728) But it doesn't seem to work for me. No errors, but no per user databases created either.

I tried both with copying the newly compiled couchdb_peruser plugin (folder name: `couch_peruser-2.0.0-RC4-4381-ga9d709714`) into my system wide installed stable couchdb instance, and also simply running the newly compiled couchdb. Per user databases won't be created when making new users with either instance of couchdb.

I'm really just a beginner with couchdb, and I don't really understand how it can happen, that such a seemingly simple and basic thing like this (ie. storing data for users that only they can see and modify)  doesn't work.

**Comment by jacksonrayhamilton** [comment]
@emoryy Did you try enabling the plugin only after your `_users` database was created?

Making it possible to enable this plugin without the `_users` database seems like it would make it much easier to use.  After or despite that, we should get this merged, as this feature is so important for any application in need of basic security.

**Comment by emoryy** [comment]
@jacksonrayhamilton Yes, I think I already had the `_users` database.

Now I actually redid the instructions of @guillett to the letter, and it seems to work - but only on that build of couchdb.

What I don't know is how to get it work with the system installed couchdb. Reinstalling it, and simply copying the newly built plugin into its lib folder (`/usr/lib/couchdb/lib/`) doesn't seem to work.

**Comment by emoryy** [comment]
I managed to run couchdb built with peruser from the test branch as a system service. At first it seemed to work quite well, but then after an hour of not touching it, I noticed that couchdb is using up one of the CPU cores entirely (beam.smp process). It also became unresponsive.
I tried to stop and restart the service, but without success. Couchdb doesn't start up anymore. [Here is the error log.](https://gist.githubusercontent.com/emoryy/18bb3c44b56299d1b06069b076601622/raw/d8484969f3f654b17090119ae36622d36f368345/gistfile1.txt)

The following info may be irrelevant regarding the problem, but this is how I got couchdb work as a system service:
I use Arch Linux, so I downloaded the [build files for the official couchdb Arch package](https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/couchdb).
Then [I modified the PKGBUILD](https://gist.github.com/emoryy/517d8643fe9648d16b700eb8aff789a6) according to the instructions of @guillett, and then simply built and installed the package replacing the official one.

**Comment by fteotini** [comment]
👍

**Comment by janl** [comment]
Hi, awesome work! I’ve opened a PR of this on couchdb.git since the couch_peruser.git repo was since moved into couchdb.git: https://github.com/apache/couchdb/pull/570

**Comment by wohali** [comment]
Merged into the new monorepo!

@guillett Please close this PR, as I'm unable to do so.

**Comment by guillett** [comment]
🚀 Great ! Thanks !

**Pull request closed without merging**
